name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Validate composer.json and composer.lock
        run: composer validate --strict
        working-directory: ./src

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader --prefer-dist --no-progress
        working-directory: ./src

      - name: Build the Docker image
        run: |
          docker build . --file build/test/Dockerfile --tag rdurica/api_example:$(echo ${{ github.ref }} | sed 's/refs\/tags\///')
          docker tag rdurica/api_example:$(echo ${{ github.ref }} | sed 's/refs\/tags\///') rdurica/api_example:latest
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        run: |
          docker push rdurica/api_example:$(echo ${{ github.ref }} | sed 's/refs\/tags\///')
          docker push rdurica/api_example:latest